import type { Metadata } from "next";
import "@/app/globals.css";
import "@/styles/index.scss";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import LayoutWithRoute from "@/layout/LayoutWithRoute";

interface LocaleLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

async function getMessages(locale: string) {
  try {
    return (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
}

export function generateStaticParams() {
  return ["vi", "en"].map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: "teky.edu.vn",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: LocaleLayoutProps) {
  const messages = await getMessages(locale);
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <LayoutWithRoute>{children}</LayoutWithRoute>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
